### PR TITLE
make sure that the release repo is available for snapshot-enabled builds as well

### PR DESCRIPTION
**Pull request by kaikreuzer**
See https://github.com/openhab/openhab2-addons/pull/6058#issuecomment-531365407

Also removed JCenter as this is included in our virtual Artifactory repo.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by wborn** [comment]
It might help to add a comment on why that repo is somewhat duplicated. 

Are you sure that profile is also used by Jenkins? AFAIK it came to existence as an easy way to skip snapshot downloads (https://github.com/openhab/openhab2-addons/pull/5089).

Later on the snapshot update policy was changed to daily (https://github.com/openhab/openhab2-addons/issues/5416, https://github.com/openhab/openhab2-addons/pull/5553) which makes it even less necessary to manually deactivate this profile to skip snapshot downloads.

**Comment by kaikreuzer** [comment]
> It might help to add a comment on why that repo is somewhat duplicated.

Added.

> Are you sure that profile is also used by Jenkins?

I wouldn't know why it shouldn't - now that we have deactivated any "circumvent repo" options on it.

> which makes it even less necessary to manually deactivate this profile

Hm, you are right, it was introduced for speed and not by @pfink for reproducible release builds (seems I remembered that incorrectly). Nonetheless I think it is a good feature that we are able to prohibit builds to reference any kind of snapshot artifacts, so I would leave the profile in place.

**Review by wborn — APPROVED** [review]
Thanks! I'd be very happy when this fixes the PR builds. :-)

**Comment by kaikreuzer** [comment]
@wborn You should now also have the rights to merge here, I added all @openhab/distro-maintainers to this repo.

**Comment by wborn** [comment]
Thanks for adding us. :+1:

**Comment by kaikreuzer** [comment]
New version is deployed to Maven Central - let's see what happens :-)

**Comment by wborn** [comment]
It seems to work! :-) Just need to fix a tiny SAT issue (https://github.com/openhab/openhab2-addons/pull/6061).

**Pull request merged**
